/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './signalr.module';
import * as import2 from '@angular/common';
import * as import3 from './signalr-hub-options';
import * as import4 from './signalr.service';
import * as import5 from './hub-factory.service';
import * as import6 from './signalr_tokens';
class SignalRModuleInjector extends import0.ɵNgModuleInjector<import1.SignalRModule> {
  _CommonModule_0:import2.CommonModule;
  _SignalRModule_1:import1.SignalRModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  _SIGNALR_URL_3:any;
  __SignalRHubOptions_4:import3.SignalRHubOptions;
  _SIGNALR_CONNECTION_5:any;
  __SignalRService_6:import4.SignalRService;
  __HubFactory_7:import5.HubFactory;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _SignalRHubOptions_4():import3.SignalRHubOptions {
    if ((this.__SignalRHubOptions_4 == null)) { (this.__SignalRHubOptions_4 = new import3.SignalRHubOptions()); }
    return this.__SignalRHubOptions_4;
  }
  get _SignalRService_6():import4.SignalRService {
    if ((this.__SignalRService_6 == null)) { (this.__SignalRService_6 = new import4.SignalRService(this._SIGNALR_CONNECTION_5,this.parent.get(import0.ErrorHandler))); }
    return this.__SignalRService_6;
  }
  get _HubFactory_7():import5.HubFactory {
    if ((this.__HubFactory_7 == null)) { (this.__HubFactory_7 = new import5.HubFactory(this._SIGNALR_CONNECTION_5)); }
    return this.__HubFactory_7;
  }
  createInternal():import1.SignalRModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._SignalRModule_1 = new import1.SignalRModule();
    this._SIGNALR_URL_3 = '/signalr';
    this._SIGNALR_CONNECTION_5 = (undefined as any);
    return this._SignalRModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.SignalRModule)) { return this._SignalRModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import6.SIGNALR_URL)) { return this._SIGNALR_URL_3; }
    if ((token === import3.SignalRHubOptions)) { return this._SignalRHubOptions_4; }
    if ((token === import6.SIGNALR_CONNECTION)) { return this._SIGNALR_CONNECTION_5; }
    if ((token === import4.SignalRService)) { return this._SignalRService_6; }
    if ((token === import5.HubFactory)) { return this._HubFactory_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SignalRModuleNgFactory:import0.NgModuleFactory<import1.SignalRModule> = new import0.NgModuleFactory<any>(SignalRModuleInjector,import1.SignalRModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVXNlci9Tb3VyY2UvUmVwb3MvYW5ndWxhci1zaWduYWxyL3NyYy9zaWduYWxyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9Vc2VyL1NvdXJjZS9SZXBvcy9hbmd1bGFyLXNpZ25hbHIvc3JjL3NpZ25hbHIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
